# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jarvisGui(object):
    def setupUi(self, jarvisGui):
        jarvisGui.setObjectName("jarvisGui")
        jarvisGui.resize(1122, 852)
        self.centralwidget = QtWidgets.QWidget(jarvisGui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1121, 851))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:/jarvis_bot_gui/JarvisGUI/Gifs/7LP8.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(900, 770, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 0, 0)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(990, 770, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 421, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:/jarvis_bot_gui/JarvisGUI/Gifs/Jarvis_Loading_Screen.gif"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(570, 30, 256, 51))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(830, 30, 256, 51))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        jarvisGui.setCentralWidget(self.centralwidget)

        self.retranslateUi(jarvisGui)
        QtCore.QMetaObject.connectSlotsByName(jarvisGui)

    def retranslateUi(self, jarvisGui):
        _translate = QtCore.QCoreApplication.translate
        jarvisGui.setWindowTitle(_translate("jarvisGui", "MainWindow"))
        self.pushButton.setText(_translate("jarvisGui", "RUN"))
        self.pushButton_2.setText(_translate("jarvisGui", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jarvisGui = QtWidgets.QMainWindow()
    ui = Ui_jarvisGui()
    ui.setupUi(jarvisGui)
    jarvisGui.show()
    sys.exit(app.exec_())
